from __future__ import annotations

import pytest
import torch

from unirl.sde.unipc import UniPCSpec, UniPCStrategy


def _step(
    strategy: UniPCStrategy,
    *,
    sample: torch.Tensor,
    noise_pred: torch.Tensor,
    sigmas: torch.Tensor,
    step_index: int,
) -> torch.Tensor:
    return strategy.denoise(
        noise_pred=noise_pred,
        sample=sample,
        sigma=sigmas[step_index],
        sigma_next=sigmas[step_index + 1],
        eta=0.0,
        step_index=step_index,
    )[0]


def test_unipc_matches_fastvideo_wan_golden_trajectory() -> None:
    """Golden values generated by FastVideo FlowUniPCMultistepScheduler."""
    sigmas = torch.tensor([1.0, 0.8, 0.55, 0.25, 0.0], dtype=torch.float32)
    noise_preds = [
        torch.tensor([[[[0.1, -0.2]]]]),
        torch.tensor([[[[0.05, 0.3]]]]),
        torch.tensor([[[[-0.4, 0.15]]]]),
        torch.tensor([[[[0.2, -0.1]]]]),
    ]
    golden = [
        torch.tensor([[[[0.2300000042, -0.4600000083]]]]),
        torch.tensor([[[[0.2205323279, -0.5653234720]]]]),
        torch.tensor([[[[0.4362622499, -0.5890948176]]]]),
        torch.tensor([[[[0.3862622380, -0.5640948415]]]]),
    ]

    strategy = UniPCStrategy()
    strategy.init_schedule(sigmas)
    sample = torch.tensor([[[[0.25, -0.5]]]])
    for step_index, noise_pred in enumerate(noise_preds):
        sample = _step(
            strategy,
            sample=sample,
            noise_pred=noise_pred,
            sigmas=sigmas,
            step_index=step_index,
        )
        torch.testing.assert_close(sample, golden[step_index], rtol=1e-6, atol=1e-6)


def test_unipc_gap_resets_multistep_history() -> None:
    sigmas = torch.tensor([1.0, 0.8, 0.55, 0.25, 0.0])
    strategy = UniPCStrategy()
    strategy.init_schedule(sigmas)

    sample = torch.tensor([[[[0.25, -0.5]]]])
    sample = _step(
        strategy,
        sample=sample,
        noise_pred=torch.tensor([[[[0.1, -0.2]]]]),
        sigmas=sigmas,
        step_index=0,
    )
    sample = _step(
        strategy,
        sample=sample,
        noise_pred=torch.tensor([[[[0.05, 0.3]]]]),
        sigmas=sigmas,
        step_index=1,
    )

    jumped_sample = torch.tensor([[[[0.4, -0.6]]]])
    jumped_pred = torch.tensor([[[[0.2, -0.1]]]])
    after_gap = _step(
        strategy,
        sample=jumped_sample,
        noise_pred=jumped_pred,
        sigmas=sigmas,
        step_index=3,
    )

    fresh = UniPCStrategy()
    fresh.init_schedule(sigmas)
    fresh_result = _step(
        fresh,
        sample=jumped_sample,
        noise_pred=jumped_pred,
        sigmas=sigmas,
        step_index=3,
    )
    torch.testing.assert_close(after_gap, fresh_result, rtol=0.0, atol=0.0)


def test_unipc_requires_schedule_and_valid_config() -> None:
    with pytest.raises(ValueError, match="solver_order"):
        UniPCStrategy(config=UniPCSpec(solver_order=0))
    with pytest.raises(ValueError, match="solver_type"):
        UniPCStrategy(config=UniPCSpec(solver_type="midpoint"))

    strategy = UniPCStrategy()
    with pytest.raises(RuntimeError, match=r"init_schedule\(\)"):
        strategy.denoise(
            noise_pred=torch.zeros(1, 1),
            sample=torch.zeros(1, 1),
            sigma=torch.tensor(1.0),
            sigma_next=torch.tensor(0.0),
            step_index=0,
        )


def test_unipc_rejects_duplicate_sigmas() -> None:
    strategy = UniPCStrategy()
    with pytest.raises(ValueError, match="strictly decreasing"):
        strategy.init_schedule(torch.tensor([1.0, 0.5, 0.5, 0.0]))
